backend:
  name: github
  repo: cetevolte/docs_test
  branch: main
  auth_type: implicit
  app_id: 0v23L1H9FSm9BXv9ZGTf

media_folder: "uploads"
public_folder: "/uploads"

collections:
  - name: "docs"
    label: "Documentazione"
    files:
      - label: "Benvenuto"
        name: "benvenuto"
        file: "benvenuto.md"
        fields:
          - { label: "Contenuto", name: "body", widget: "markdown" }
