backend:
  name: git-gateway
  branch: main

media_folder: "uploads"
public_folder: "/uploads"

collections:
  - name: "docs"
    label: "Documentazione"
    files:
      - label: "Benvenuto"
        name: "benvenuto"
        file: "benvenuto.md"
        fields:
          - { label: "Contenuto", name: "body", widget: "markdown" }
